-record(localeinfo_struct, {locinfo = eqc_c_undefined, mbcinfo = eqc_c_undefined}).
-record(div_t, {quot = eqc_c_undefined, 'rem' = eqc_c_undefined}).
-record(ldiv_t, {quot = eqc_c_undefined, 'rem' = eqc_c_undefined}).
-record(lldiv_t, {quot = eqc_c_undefined, 'rem' = eqc_c_undefined}).
-record(queue, {inp = eqc_c_undefined, outp = eqc_c_undefined, size = eqc_c_undefined, buf = eqc_c_undefined}).
